# Generated by Django 2.1.2 on 2018-11-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('tamano', models.CharField(max_length=30)),
                ('peso', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('descripción', models.TextField()),
                ('fechaRescate', models.DateField()),
                ('estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='R', max_length=1)),
            ],
        ),
    ]
