# Generated by Django 2.1.2 on 2018-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioPerris', '0003_adoptante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='tipoVivienda',
            field=models.CharField(max_length=30),
        ),
    ]
