# Generated by Django 2.1.2 on 2018-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioPerris', '0004_auto_20181201_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='pefechaNacimiento',
            field=models.CharField(max_length=12),
        ),
    ]
