# Generated by Django 2.1.2 on 2018-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioPerris', '0005_auto_20181201_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='tipoVivienda',
            field=models.CharField(max_length=50),
        ),
    ]
